name: 'Test'

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          # cache: npm

      - name: Install NPM packages
        run: npm install

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: bin/rake
